### ISSUE TITLE
Socket Exception by using icap-client with File

### ISSUE THREAD

**Issue by christianhenle** [claudineynascimento/icap-client#1]
Hallo,

thank you for providing your icap-Library on Github. 
First i used your icap-Library to call my icap-server without uploading any file this works fine. The response Message from server contains status code 204. 
But when i added a file with the setHttpRequestBody-Method i getting an exception.
This is my stacktracke:

Exception in thread "main" net.rfc3507.client.ICAPException: java.net.SocketException: Connection reset by peer: socket write error
	at net.rfc3507.client.ICAPClient.execute(ICAPClient.java:94)
	at net.rfc3507.client.Main.main(Main.java:24)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at net.rfc3507.client.ICAPClient.performAdaptation(ICAPClient.java:211)
	at net.rfc3507.client.ICAPClient.execute(ICAPClient.java:92)
	... 1 more

My Main-Method to use your library was:

        final String SERVER = "myserver";
        final int PORT = 1344;
        final String SERVICE = "AVSCAN";

        File files = new File("C:\\dev\\8473.PNG");
        System.out.println(files.toPath());

        ICAPClient icapClient = new ICAPClient(SERVER, PORT);
        ICAPRequest icapRequest = new ICAPRequest(SERVICE, ICAPRequest.Mode.REQMOD);
        //icapRequest.setHttpRequestBody(files);
        byte[] fileContent = Files.readAllBytes(files.toPath());
        icapRequest.setHttpRequestBody(fileContent);
        ICAPResponse icapResponse = icapClient.execute(icapRequest);
        System.out.println(icapResponse.toString());

**Comment by claudineyns** [comment]
Hello!
Thank you for your feedback.
I am going to check your issue.

**Comment by claudineyns** [comment]
Hi,

I have tested your snippet against ClamAV icap server on linux, Debian distro, and no exception was thrown.

I have noticed your snipped did not provide a "HTTP Request Header" input; I believe some icap-server implementation require a request header input in order to work together a request body, and some does not.

I would like to ask you to make some changes on your code and try again; please check whether the issue still occurs:

```
final String SERVER = "myserver";
final int PORT = 1344;
final String SERVICE = "AVSCAN";

File files = new File("C:\\dev\\8473.PNG");
System.out.println(files.toPath());

ICAPClient icapClient = new ICAPClient(SERVER, PORT);
ICAPRequest icapRequest = new ICAPRequest(SERVICE, ICAPRequest.Mode.REQMOD);
//icapRequest.setHttpRequestBody(files);
byte[] fileContent = Files.readAllBytes(files.toPath());
//------------------------------------------------------------------------------
String contentType = "image/png";
String resource = files.getName();
String requestHeader 
      		= "POST /"+resource+" HTTP/1.1\r\n"
      		+ "Host: localhost\r\n"
       		+ "User-Agent: Java-ICAP-Client/1.0\r\n"
       		+ "Content-Type: "+contentType+"\r\n"
       		+ "Content-Length: "+fileContent.length+"\r\n"
       		+ "\r\n";
icapRequest.setHttpRequestHeader(requestHeader.getBytes());
//------------------------------------------------------------------------------
icapRequest.setHttpRequestBody(fileContent);
ICAPResponse icapResponse = icapClient.execute(icapRequest);
System.out.println(icapResponse.toString());
```
